services:

  backend:
    build:
      context: ./backend

    container_name: backend-api

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    env_file:
      - path: .env
        required: false

    environment:
      OLLAMA_HOST: http://ollama:11434

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/')"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 120s

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend

    container_name: frontend-app

    ports:
      - "8501:8501"

    volumes:
      - ./frontend:/app

    depends_on:
      backend:
        condition: service_healthy

    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest

    container_name: ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    restart: unless-stopped


volumes:
  ollama_data: