services:
  backend:
    build:
      context: ./backend

    container_name: backend-api

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    env_file:
      - .env

    restart: unless-stopped