services:

  backend:
    build:
      context: ./backend

    container_name: backend-api

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    env_file:
      - .env

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend

    container_name: frontend-app

    ports:
      - "8501:8501"

    volumes:
      - ./frontend:/app

    depends_on:
      - backend

    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest

    container_name: ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    restart: unless-stopped


volumes:
  ollama_data: